# Generated by Django 5.0.6 on 2024-06-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0002_remove_books_titre_books_title_alter_books_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='titre',
            new_name='titre',
        ),
    ]
