# Generated by Django 5.0.6 on 2024-06-29 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0003_rename_title_books_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ville',
        ),
        
    ]
