# Generated by Django 5.0.6 on 2024-06-29 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0004_remove_books_titre_remove_user_ville_books_title'),
    ]

    operations = [
    ]
