# Generated by Django 5.0.6 on 2024-06-29 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0005_remove_books_titre_books_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
