# Generated by Django 5.0.6 on 2024-06-30 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0007_remove_books_titre_books_title_alter_loans_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='resume',
            field=models.CharField( default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='book_image'),
            preserve_default=False,
        ),
    ]
