# Generated by Django 5.0.6 on 2024-06-30 23:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0008_remove_books_titre_books_resume_books_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_image'),
        ),
    ]
